# -----------------------------------------------------
#                     USERS
# -----------------------------------------------------
# CREATE User
POST http://localhost:4040/users/register 
# -----------------------------------------------------
# Get User Details
GET http://localhost:4040/users/user/1 
# -----------------------------------------------------
# SoftDeleteUser User
DELETE http://localhost:4040/users/1 
# -----------------------------------------------------
#  update User
PUT http://localhost:4040/users/update/user/1 
# -----------------------------------------------------
# Login User
POST http://localhost:4040/users/login
# -----------------------------------------------------
#                         END
# -----------------------------------------------------
